// Generated by Unloop
// Smart Coffee Maker

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_brew_start_clicked(|| {
        println!("brew_start clicked");
    });
    
    app.on_clean_clicked(|| {
        println!("clean clicked");
    });
    

    
    app.run()
}
